# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
